version: "2.4"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/data:rw
    networks:
      back:
        aliases:
         - prometheus
    expose:
      - 9090
    cpus: '0.5'
    mem_limit: 100M
    depends_on:
      - cadvisor
      - node-exporter   
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro    
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    networks:
      back:
        aliases:
         - exporter
    cpus: '0.5'
    mem_limit: 100M
    expose:
      - 9100
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      back:
        aliases:
         - cadvisor
    cpus: '0.5'
    mem_limit: 100M
    expose:
      - 8080
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana_db:/var/lib/grafana
    env_file:
      - grafana.config
    networks:
      back:
        aliases:
         - grafana
      front:
    ports:
      - '3000:3000'
    cpus: '1.0'
    mem_limit: 100M
    depends_on:
      - prometheus

networks:
  front:
    driver: bridge
  back:

volumes:
  prometheus_data:
  grafana_db:
